<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
    'mountains_index' => [[], ['_controller' => 'App\\Controller\\MountainsController::index'], [], [['text', '/mountains/']], [], []],
    'mountains_new' => [[], ['_controller' => 'App\\Controller\\MountainsController::new'], [], [['text', '/mountains/new']], [], []],
    'mountains_show' => [['id'], ['_controller' => 'App\\Controller\\MountainsController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/mountains']], [], []],
    'mountains_edit' => [['id'], ['_controller' => 'App\\Controller\\MountainsController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/mountains']], [], []],
    'mountains_delete' => [['id'], ['_controller' => 'App\\Controller\\MountainsController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/mountains']], [], []],
    'usuario_sube_index' => [[], ['_controller' => 'App\\Controller\\UsuarioSubeController::index'], [], [['text', '/usuario/sube/']], [], []],
    'usuario_sube_new' => [[], ['_controller' => 'App\\Controller\\UsuarioSubeController::new'], [], [['text', '/usuario/sube/new']], [], []],
    'usuario_sube_show' => [['id'], ['_controller' => 'App\\Controller\\UsuarioSubeController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/usuario/sube']], [], []],
    'usuario_sube_edit' => [['id'], ['_controller' => 'App\\Controller\\UsuarioSubeController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/usuario/sube']], [], []],
    'usuario_sube_delete' => [['id'], ['_controller' => 'App\\Controller\\UsuarioSubeController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/usuario/sube']], [], []],
    'usuarios_index' => [[], ['_controller' => 'App\\Controller\\UsuariosController::index'], [], [['text', '/usuarios/']], [], []],
    'usuarios_new' => [[], ['_controller' => 'App\\Controller\\UsuariosController::new'], [], [['text', '/usuarios/new']], [], []],
    'usuarios_show' => [['id'], ['_controller' => 'App\\Controller\\UsuariosController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/usuarios']], [], []],
    'usuarios_edit' => [['id'], ['_controller' => 'App\\Controller\\UsuariosController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/usuarios']], [], []],
    'usuarios_delete' => [['id'], ['_controller' => 'App\\Controller\\UsuariosController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/usuarios']], [], []],
    'zonas_index' => [[], ['_controller' => 'App\\Controller\\ZonasController::index'], [], [['text', '/zonas/']], [], []],
    'zonas_new' => [[], ['_controller' => 'App\\Controller\\ZonasController::new'], [], [['text', '/zonas/new']], [], []],
    'zonas_show' => [['id'], ['_controller' => 'App\\Controller\\ZonasController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/zonas']], [], []],
    'zonas_edit' => [['id'], ['_controller' => 'App\\Controller\\ZonasController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/zonas']], [], []],
    'zonas_delete' => [['id'], ['_controller' => 'App\\Controller\\ZonasController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/zonas']], [], []],
    'easyadmin' => [[], ['_controller' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Controller\\EasyAdminController::indexAction'], [], [['text', '/admin/']], [], []],
];
